name: Build and Push Docker image

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发
    tags:
      - '*'  # 当有标签推送时触发
  pull_request:
    branches:
      - main  # 当向 main 分支提交 PR 时触发

jobs:
  build:
    runs-on: ubuntu-20.04  # 使用 Ubuntu 20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'  # 仅在非 PR 事件中执行
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract GitHub tag
        id: extract_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set Docker image tag
        id: image_tag
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
              echo "tag=latest" >> $GITHUB_ENV
          elif [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
              echo "tag=pr-1" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
              echo "tag=unknown" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false  # 默认不推送
          platforms: linux/amd64,linux/arm64  # 指定多平台
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scipopt-docker:${{ env.tag }}

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true  # 推送镜像
          platforms: linux/amd64,linux/arm64  # 指定多平台
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scipopt-docker:${{ env.tag }}